module.exports.userService = require('./user.service')
module.exports.authService = require('./auth.service')
module.exports.candidateService = require('./candidate.service')
module.exports.interviewService = require('./interview.service')
module.exports.uploadService = require('./upload.service')
module.exports.transcriptionService = require('./transcription.service')